[package]
name = "kernel8"
version = "0.1.0"
authors = ["Andre Richter <andre.o.richter@gmail.com>"]

[dependencies]
raspi3_boot = { path = "raspi3_boot" }
register = "0.1.1"

[package.metadata.cargo-xbuild]
sysroot_path = "../xbuild_sysroot"
